using System.Collections.Immutable;
using System.Text.Json.Serialization;

namespace CardLab.Game;

public sealed record CardDefinition
{
    public string Name { get; init; } = "Ma super carte";
    
    // Description will soon be something that will only be generated by the server.
    public string Description { get; init; } = "";
    
    // This is what the user can edit and refer to as "description".
    public string Lore { get; init; } = "";
    
    // For now, only units can be made.
    // So yeah, this property is a bit of a joke...

    public CardType Type { get; init; } = CardType.Unit;

    public int Attack { get; init; } = 5;
    public int Health { get; init; } = 5;
    public int Cost { get; init; } = 5;

    public CardScript? Script { get; init; } = null;
}

public sealed record CardScript
{
    public ImmutableArray<CardEventHandler> Handlers { get; init; } = [];
}

public sealed record CardEventHandler
{
    public required CardEvent Event { get; init; }
    
    public ImmutableArray<CardAction> Actions { get; init; } = [];
}

[JsonPolymorphic(TypeDiscriminatorPropertyName = "type")]
[JsonDerivedType(typeof(DrawCardCardAction), typeDiscriminator: "drawCard")]
[JsonDerivedType(typeof(WinGameCardAction), typeDiscriminator: "winGame")]
[JsonDerivedType(typeof(HurtAction), typeDiscriminator: "hurt")]
public abstract record CardAction;

// i hate this name btw
public sealed record DrawCardCardAction(int NumCards) : CardAction;

public sealed record WinGameCardAction : CardAction;

public sealed record HurtAction(int Damage, Target Target) : CardAction;

[JsonPolymorphic(TypeDiscriminatorPropertyName = "type")]
[JsonDerivedType(typeof(RandomEnemyTarget), typeDiscriminator: "randomEnemy")]
[JsonDerivedType(typeof(EnemyCoreTarget), typeDiscriminator: "enemyCore")]
[JsonDerivedType(typeof(MyCoreTarget), typeDiscriminator: "myCore")]
public abstract record Target;

public sealed record RandomEnemyTarget : Target;

public sealed record EnemyCoreTarget : Target;

public sealed record MyCoreTarget : Target;

public enum CardEvent
{
    WhenISpawn,
    WhenIDie,
    WhenIGetHurt,
    WhenIAttack,
    WhenPlayerDrawsAnyCard,
    WhenPlayerDrawsMe
}

public enum CardType
{
    Unit,
    Spell
}