using System.Collections.Immutable;
using System.Text.Json.Serialization;

namespace CardLab.Game;

public sealed record CardDefinition
{
    public string Name { get; init; } = "Ma super carte";
    
    // Description will soon be something that will only be generated by the server.
    public string Description { get; init; } = "";
    
    // This is what the user can edit and refer to as "description".
    public string Lore { get; init; } = "";
    
    // For now, only units can be made.
    // So yeah, this property is a bit of a joke...

    public CardType Type { get; init; } = CardType.Unit;

    public int Attack { get; init; } = 5;
    public int Health { get; init; } = 5;
    public int Cost { get; init; } = 5;

    public CardScript? Script { get; init; } = null;
}

public sealed record CardScript
{
    public ImmutableArray<CardEventHandler> Handlers { get; init; } = [];
}

public sealed record CardEventHandler
{
    public required CardEvent Event { get; init; }
    
    public ImmutableArray<CardAction> Actions { get; init; } = [];
}

[JsonPolymorphic(TypeDiscriminatorPropertyName = "type")]
[JsonDerivedType(typeof(DrawCardCardAction), typeDiscriminator: "drawCard")]
public abstract record CardAction;

// i hate this name btw
public record DrawCardCardAction : CardAction;

public enum CardEvent
{
    WhenISpawn,
    WhenIDie,
    WhenIGetHurt,
    WhenIAttack,
    WhenPlayerDrawsAnyCard,
    WhenPlayerDrawsMe
}

public enum CardType
{
    Unit,
    Spell
}